Added few items to "Java useful libs" list
atinfo/awesome-test-automation pull request #403
Opened 2021-02-20 13:19 UTC by RSheremeta

Added:

- https://github.com/RSheremeta/TestRail-JUnit - This Library helps you to integrate your JUnit-based tests with TestRail in an easily manner. 
- https://github.com/RSheremeta/TestRail-TestNG - This Library helps you to integrate your TestNG-based tests with TestRail in an easily manner.
- https://github.com/RSheremeta/Allure-Environment-Creator - This tiny Library helps you to serve and store environment data for Allure easily.

2021-04-22 07:57 UTC, GastonAGenaud commented
Nice!

2021-06-29 10:33 UTC, dc-avasilev commented on java-test-automation.md
> +* [TestRail-JUnit](https://github.com/RSheremeta/TestRail-JUnit) - This Library helps you to integrate your JUnit-based tests with TestRail in an easily manner.
plz, delete space in the end

2021-06-29 10:36 UTC, dc-avasilev requested changes
need some small fix

2021-07-01 11:56 UTC, RSheremeta commented on java-test-automation.md
> +* [TestRail-JUnit](https://github.com/RSheremeta/TestRail-JUnit) - This Library helps you to integrate your JUnit-based tests with TestRail in an easily manner.
fixed

2021-07-01 13:12 UTC, dc-avasilev approved these changes

2021-07-30 22:30 UTC, merged